---
dist: xenial
language: java
sudo: false
jdk:
  - openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
addons:
  - sonarcloud:
    organization: "attilabogar-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
